# On n'importe les deux libraries numpy et pandas

In [1]:
import numpy as np
import pandas as pd
df_animaux=pd.read_csv(r"C:\Users\MHPH6515\Desktop\ESLSCA\data analyse\fr_animaux.csv") 
df_cereales=pd.read_csv(r"C:\Users\MHPH6515\Desktop\ESLSCA\data analyse\fr_cereales.csv")  
df_population=pd.read_csv(r"C:\Users\MHPH6515\Desktop\ESLSCA\data analyse\fr_population.csv")  
df_alim=pd.read_csv(r"C:\Users\MHPH6515\Desktop\ESLSCA\data analyse\fr_sousalimentation.csv")  
df_veg=pd.read_csv(r"C:\Users\MHPH6515\Desktop\ESLSCA\data analyse\fr_vegetaux.csv")  
#pd.set_option("display.max_rows", None, "display.max_columns", None)

In [2]:
l = df_population.loc[[33,34,35,36,37]]

In [3]:
#On crée une copie de la table population
df_population_1 = df_population
#On supprime les données déclarées en double
df_population_1 = df_population_1.drop(33, axis=0).reset_index()
#on garde que les champs utiles
df_population_1 = df_population_1[['Zone', 'Code zone', 'Valeur']]
df_population_1

                                       Zone  Code zone  Valeur
0                               Afghanistan          2   30552
1                            Afrique du Sud        202   52776
2                                   Albanie          3    3173
3                                   Algérie          4   39208
4                                 Allemagne         79   82727
..                                      ...        ...     ...
169  Venezuela (République bolivarienne du)        236   30405
170                                Viet Nam        237   91680
171                                   Yémen        249   24407
172                                  Zambie        251   14539
173                                Zimbabwe        181   14150

[174 rows x 3 columns]

In [4]:
#On supprime les doublons et on calcul la population mondiale en 2013
df_population_1 = df_population_1.drop_duplicates()
population_mondiale = str(df_population_1['Valeur'].sum(skipna=True)* 1000)
print("Population totale en 2013 : " + population_mondiale)

Population totale en 2013 : 6997326000

In [5]:
df_animaux_1 = df_animaux
df_animaux_1['origine'] = 'animal'
df_vegetaux_1 = df_veg
df_vegetaux_1['origine'] = 'vegetal'
df_ani_veg = df_animaux_1.append(df_vegetaux_1)

#maskhatch biha 
#idx = np.where(( (df_ani_veg['Élément']=="Production") | (df_ani_veg['Produit']=="Viande de Bovins") ))
# 'Disponibilité alimentaire (Kcal/personne/jour)',
 # 'Disponibilité de protéines en quantité (g/personne/jour)']), 

df_ani_veg_clean1 = df_ani_veg.loc[df_ani_veg['Élément']=='Disponibilité alimentaire en quantité (kg/personne/an)']
df_ani_veg_clean2 = df_ani_veg.loc[df_ani_veg['Élément']=='Disponibilité alimentaire (Kcal/personne/jour)']
df_ani_veg_clean3 = df_ani_veg.loc[df_ani_veg['Élément']=='Disponibilité de protéines en quantité (g/personne/jour)']
df_ani_veg_clean4 = df_ani_veg.loc[df_ani_veg['Élément']=='Disponibilité intérieure']
df_ani_veg_clean5 = df_ani_veg.loc[df_ani_veg['Élément']=='Nourriture']

df_ani_veg_clean6 = df_ani_veg_clean1.append(df_ani_veg_clean2)
df_ani_veg_clean7 = df_ani_veg_clean6.append(df_ani_veg_clean3)
df_ani_veg_clean8 = df_ani_veg_clean7.append(df_ani_veg_clean4)
df_ani_veg_clean = df_ani_veg_clean8.append(df_ani_veg_clean5)

df_ani_veg_clean = pd.pivot_table(df_ani_veg_clean, index=['Code zone', 'Zone', 'Code Produit', 'Produit', 'origine'], columns = 'Élément', values = 'Valeur', aggfunc=np.sum, fill_value=0).reset_index()

df_ani_veg_clean = pd.merge(df_ani_veg_clean, df_population_1, on =['Zone', 'Code zone'])

df_ani_veg_clean['dispo_alimentaire_kg']=df_ani_veg_clean['Disponibilité alimentaire en quantité (kg/personne/an)']*df_ani_veg_clean['Valeur']*1000
df_ani_veg_clean['dispo_alimentaire_kcal']=df_ani_veg_clean['Disponibilité alimentaire (Kcal/personne/jour)']*df_ani_veg_clean['Valeur']*1000*365
df_ani_veg_clean['dispo_protéine_Kg']=df_ani_veg_clean['Disponibilité de protéines en quantité (g/personne/jour)']*df_ani_veg_clean['Valeur']*365
#df_ani_veg_clean = df_ani_veg_clean.drop_duplicates().reset_index()
df_ani_veg_clean.head()

,Code zone,Zone,Code Produit,Produit,origine,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Nourriture,Valeur,dispo_alimentaire_kg,dispo_alimentaire_kcal,dispo_protéine_Kg
0,1,Arménie,2511,Blé,vegetal,1024,130.60,30.52,554,389,2977,388796200.0,1112683520000,33163184.60
1,1,Arménie,2513,Orge,vegetal,0,0.00,0.00,198,0,2977,0.0,0,0.00
2,1,Arménie,2514,Maïs,vegetal,0,0.03,0.01,102,0,2977,89310.0,0,10866.05
3,1,Arménie,2515,Seigle,vegetal,1,0.12,0.02,1,0,2977,357240.0,1086605000,21732.10
4,1,Arménie,2516,Avoine,vegetal,2,0.37,0.09,6,1,2977,1101490.0,2173210000,97794.45

In [6]:
df_ani_veg_clean['Ratio énergie/poids']=df_ani_veg_clean['dispo_alimentaire_kcal']/df_ani_veg_clean['dispo_alimentaire_kg']
df_ani_veg_clean.head()

,Code zone,Zone,Code Produit,Produit,origine,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Nourriture,Valeur,dispo_alimentaire_kg,dispo_alimentaire_kcal,dispo_protéine_Kg,Ratio énergie/poids
0,1,Arménie,2511,Blé,vegetal,1024,130.60,30.52,554,389,2977,388796200.0,1112683520000,33163184.60,2861.868300
1,1,Arménie,2513,Orge,vegetal,0,0.00,0.00,198,0,2977,0.0,0,0.00,NaN
2,1,Arménie,2514,Maïs,vegetal,0,0.03,0.01,102,0,2977,89310.0,0,10866.05,0.000000
3,1,Arménie,2515,Seigle,vegetal,1,0.12,0.02,1,0,2977,357240.0,1086605000,21732.10,3041.666667
4,1,Arménie,2516,Avoine,vegetal,2,0.37,0.09,6,1,2977,1101490.0,2173210000,97794.45,1972.972973

In [7]:
df_ani_veg_clean.groupby('Produit',as_index=False).agg({"Ratio énergie/poids": "mean"}).sort_values(by="Ratio énergie/poids",ascending=False).replace([np.inf, -np.inf], np.nan).dropna().reset_index()[0:20]

    index                   Produit  Ratio énergie/poids
0      39            Huile de Palme          8713.419149
1      41             Huile de Soja          8625.483876
2      42       Huile de Son de Riz          8497.969939
3      37   Huile de Colza&Moutarde          8368.869607
4      32   Huil Plantes Oleif Autr          8246.215771
5      33    Huile Graines de Coton          8177.340910
6      40        Huile de Palmistes          7885.602997
7      38    Huile de Germe de Maïs          7827.167158
8      35             Huile d'Olive          7774.263485
9      30    Graisses Animales Crue          7579.278844
10     46        Huiles de Poissons          7133.945055
11     10              Beurre, Ghee          6946.278887
12      6    Arachides Decortiquees          5466.324644
13     87                    Sésame          5010.932143
14     24             Feve de Cacao          4343.034036
15     79          Riz (Eq Blanchi)          3640.609092
16     45  Huiles de Foie de Poisso          3633.539548
17     83             Sucre Eq Brut          3578.891980
18     31                  Haricots          3256.453914
19     84      Sucre non centrifugé          3254.135701

In [8]:
df_ani_veg_clean['Protéine%']=(df_ani_veg_clean['dispo_protéine_Kg']/df_ani_veg_clean['dispo_alimentaire_kg'])*100

df_ani_veg_clean.groupby('Produit',as_index=False).agg({"Protéine%": "mean"}).sort_values(by="Protéine%",ascending=False).replace([np.inf, -np.inf], np.nan).dropna().reset_index()[0:20]

    index                   Produit  Protéine%
0       6    Arachides Decortiquees  24.790816
1      81                      Soja  24.757947
2      50       Légumineuses Autres  22.025876
3      70                      Pois  21.953510
4      31                  Haricots  21.574261
5       0          Abats Comestible  17.630901
6      95             Viande, Autre  17.410158
7      87                    Sésame  17.337451
8      69  Plantes Oleiferes, Autre  15.609502
9       3     Aliments pour enfants  14.872622
10     92          Viande de Bovins  14.461108
11     16              Cephalopodes  14.057333
12     90    Viande d'Ovins/Caprins  13.736265
13     94       Viande de Volailles  12.620016
14     73       Poissons Pelagiques  12.129966
15     67                   Piments  10.985559
16     27    Graines Colza/Moutarde  10.950000
17     72   Poissons Marins, Autres  10.942450
18     58                     Oeufs  10.696134
19     97            Épices, Autres  10.679380

In [9]:
#Questio 7
df1=df_ani_veg_clean[df_ani_veg_clean['origine']=='vegetal']
df1 = df1.replace([-np.inf, np.inf], np.nan)
df1

,Code zone,Zone,Code Produit,Produit,origine,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Nourriture,Valeur,dispo_alimentaire_kg,dispo_alimentaire_kcal,dispo_protéine_Kg,Ratio énergie/poids,Protéine%
0,1,Arménie,2511,Blé,vegetal,1024,130.60,30.52,554,389,2977,388796200.0,1112683520000,33163184.60,2861.868300,8.529709
1,1,Arménie,2513,Orge,vegetal,0,0.00,0.00,198,0,2977,0.0,0,0.00,NaN,NaN
2,1,Arménie,2514,Maïs,vegetal,0,0.03,0.01,102,0,2977,89310.0,0,10866.05,0.000000,12.166667
3,1,Arménie,2515,Seigle,vegetal,1,0.12,0.02,1,0,2977,357240.0,1086605000,21732.10,3041.666667,6.083333
4,1,Arménie,2516,Avoine,vegetal,2,0.37,0.09,6,1,2977,1101490.0,2173210000,97794.45,1972.972973,8.878378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15585,276,Soudan,2659,"Alcool, non Comestible",vegetal,0,0.00,0.00,0,0,37964,0.0,0,0.00,NaN,NaN
15586,276,Soudan,2680,Aliments pour enfants,vegetal,0,0.00,0.00,0,0,37964,0.0,0,0.00,NaN,NaN
15597,276,Soudan,2745,Miel,vegetal,0,0.02,0.00,1,1,37964,759280.0,0,0.00,0.000000,0.000000
15602,276,Soudan,2805,Riz (Eq Blanchi),vegetal,14,1.27,0.28,49,48,37964,48214280.0,193996040000,3879920.80,4023.622047,8.047244
15604,276,Soudan,2899,Miscellanees,vegetal,7,0.00,1.47,0,0,37964,0.0,96998020000,20369584.20,NaN,NaN

In [10]:
df1['Dispo_int_kcal']=df1['Disponibilité intérieure']*1000000* df1['Ratio énergie/poids']

df1

,Code zone,Zone,Code Produit,Produit,origine,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Nourriture,Valeur,dispo_alimentaire_kg,dispo_alimentaire_kcal,dispo_protéine_Kg,Ratio énergie/poids,Protéine%,Dispo_int_kcal
0,1,Arménie,2511,Blé,vegetal,1024,130.60,30.52,554,389,2977,388796200.0,1112683520000,33163184.60,2861.868300,8.529709,1.585475e+12
1,1,Arménie,2513,Orge,vegetal,0,0.00,0.00,198,0,2977,0.0,0,0.00,NaN,NaN,NaN
2,1,Arménie,2514,Maïs,vegetal,0,0.03,0.01,102,0,2977,89310.0,0,10866.05,0.000000,12.166667,0.000000e+00
3,1,Arménie,2515,Seigle,vegetal,1,0.12,0.02,1,0,2977,357240.0,1086605000,21732.10,3041.666667,6.083333,3.041667e+09
4,1,Arménie,2516,Avoine,vegetal,2,0.37,0.09,6,1,2977,1101490.0,2173210000,97794.45,1972.972973,8.878378,1.183784e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15585,276,Soudan,2659,"Alcool, non Comestible",vegetal,0,0.00,0.00,0,0,37964,0.0,0,0.00,NaN,NaN,NaN
15586,276,Soudan,2680,Aliments pour enfants,vegetal,0,0.00,0.00,0,0,37964,0.0,0,0.00,NaN,NaN,NaN
15597,276,Soudan,2745,Miel,vegetal,0,0.02,0.00,1,1,37964,759280.0,0,0.00,0.000000,0.000000,0.000000e+00
15602,276,Soudan,2805,Riz (Eq Blanchi),vegetal,14,1.27,0.28,49,48,37964,48214280.0,193996040000,3879920.80,4023.622047,8.047244,1.971575e+11
15604,276,Soudan,2899,Miscellanees,vegetal,7,0.00,1.47,0,0,37964,0.0,96998020000,20369584.20,NaN,NaN,NaN

In [11]:
#question 7 
Somme_dispo_interne=round(df1['Dispo_int_kcal'].sum(skipna=True),2)
print('Disponibilité intérieure issue des produits d\'origine végétale : ' + str(Somme_dispo_interne) + ' kcal.')

Disponibilité intérieure issue des produits d'origine végétale : 1.2166421524173388e+16 kcal.

In [12]:
#question 8
# On considère que la consommation moyenne en calories d'un être humain est de 2000 kcal
nombre_humains_kcal=df1['Dispo_int_kcal'].sum(skipna=True)/ (2000*365)
pourcentage_humains_kcal=nombre_humains_kcal/(df_population_1['Valeur'].sum(skipna=True)* 1000)

print('Pourcentage d\'humains nourris avec les calories de la disponibilité intérieure: ' 
     + str(pourcentage_humains_kcal*100) + " %")

Pourcentage d'humains nourris avec les calories de la disponibilité intérieure: 238.1814260909387 %

In [13]:
df1['dispo_int_prot']=(df1['Disponibilité intérieure'] * 1000000) * (df1['Protéine%']/100)
dispo_int_veg_prot = round(df1['dispo_int_prot'].sum(skipna=True),2)
print('Disponibilité intérieure issue des produits d\'origine végétale : ' + str(dispo_int_veg_prot) + ' kg de protéines.')

Disponibilité intérieure issue des produits d'origine végétale : 291995825800.39 kg de protéines.

In [14]:
# On considère que la consommation moyenne en protéines d'un être humain est de 50 g par jour
nbre_humains_proteine = dispo_int_veg_prot / (50 * 1000 * 365)
pourcentage_humains_proteine = (nbre_humains_proteine / df_population_1['Valeur'].sum(skipna=True)* 1000)
print('Pourcentage d\'humains nourris  avec les protéines de la disponibilité intérieure: '  
     + str(pourcentage_humains_proteine) +  ' %')

Pourcentage d'humains nourris  avec les protéines de la disponibilité intérieure: 2.2865550750006074 %

In [15]:
#question 9
df_ani_veg_clean['Nourriture_Kcal']=df_ani_veg_clean['Nourriture']*1000000*df_ani_veg_clean['Ratio énergie/poids']
df_ani_veg_clean = df_ani_veg_clean.replace([-np.inf, np.inf], np.nan)
# On somme sur la colonne de 'Nourriture_Kcal' pour avoir la nouriture disponible mondialement 
dispo_Nour_total_Kcal = df_ani_veg_clean['Nourriture_Kcal'].sum(skipna=True)
print('Nourriture totale disponible mondialement : ' + str(dispo_Nour_total_Kcal) + ' kcal.')

Nourriture totale disponible mondialement : 7357936865086520.0 kcal.

In [16]:
# On considère que la consommation moyenne en calories d'un être humain est de 2000 kcal
nombre_humains_kcal=dispo_Nour_total_Kcal/ (2000*365)
pourcentage_humains_kcal=nombre_humains_kcal/(df_population_1['Valeur'].sum(skipna=True)* 1000)
print('Pourcentage d\'humains nourris avec les calories de la disponibilité alimentaire: ' + str(pourcentage_humains_kcal*100) + " %")

Pourcentage d'humains nourris avec les calories de la disponibilité alimentaire: 144.04596225203272 %

In [17]:
# question 9 proteines
df_ani_veg_clean['Nourriture_prot']=df_ani_veg_clean['Nourriture']*1000000*df_ani_veg_clean['Protéine%']
# On somme sur la colonne de 'Nourriture_Kcal' pour avoir la nouriture disponible mondialement 
dispo_Nour_total_prot = df_ani_veg_clean['Nourriture_prot'].sum(skipna=True)
print('Nourriture totale disponible mondialement en proteines : ' + str(dispo_Nour_total_prot) + '.')

# On considère que la consommation moyenne en protéines d'un être humain est de 50 g par jour

nbre_humains_proteine = dispo_Nour_total_prot / (50 * 1000 * 365)
pourcentage_humains_proteine = (nbre_humains_proteine / df_population_1['Valeur'].sum(skipna=True)* 1000)
print('Pourcentage d\'humains nourris  avec les protéines de la disponibilité intérieure: '  
     + str(pourcentage_humains_proteine) +  ' %')

Nourriture totale disponible mondialement en proteines : 20715347668530.36.
Pourcentage d'humains nourris  avec les protéines de la disponibilité intérieure: 162.21733037464818 %

In [96]:
#question 10:
pd.set_option("display.max_rows", None, "display.max_columns", None)
df_alim_2013 = df_alim.loc[df_alim['Année']=='2012-2014'].reset_index()


#df_alim_2013 = pd.pivot_table(df_alim, index=['Code zone', 'Zone', 'Code Produit', 'Année'], columns = 'Produit', values = 'Valeur', aggfunc=np.sum, fill_value=0).reset_index()


df_alim_2013 = df_alim_2013[['Zone', 'Valeur']]

df_alim_2013 = df_alim_2013.drop(37, axis=0).reset_index()



df_alim_2013.head()

   index            Zone Valeur
0      0     Afghanistan    7.9
1      1  Afrique du Sud    2.6
2      2         Albanie    0.2
3      3         Algérie    1.7
4      4       Allemagne    NaN

In [97]:
df_alim_2013 = df_alim_2013.replace([-np.inf, np.inf], np.nan)

df_alim_2013 = df_alim_2013.replace('<0.1', 0.1)
df_alim_2013['Valeur'] = df_alim_2013['Valeur'].astype(float)
sous_alim = df_alim_2013['Valeur'].sum(skipna=True)*1000000
print('sous aliments totale en 2013 : ' + str(sous_alim))

sous aliments totale en 2013 : 746000000.0

In [98]:
val = sous_alim/(df_population_1['Valeur'].sum(skipna=True)* 1000)*100
print('le pourcentage des sous aliments dans le monde en 2013 est : ' + str(val) +'%')

le pourcentage des sous aliments dans le monde en 2013 est : 10.661215441441488%